version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rapidorch:rapidorch@postgres:5432/rapidorch
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - redis
      - chroma
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - rapidorch-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rapidorch
      - POSTGRES_USER=rapidorch
      - POSTGRES_PASSWORD=rapidorch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rapidorch-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rapidorch-network

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - rapidorch-network

  # Development services
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@rapidorch.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - rapidorch-network
    profiles:
      - dev

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - rapidorch-network
    profiles:
      - dev

volumes:
  postgres_data:
  redis_data:
  chroma_data:

networks:
  rapidorch-network:
    driver: bridge 